require 'test_helper'

class MessageTest < ActiveSupport::TestCase
  
   # negative test
   test "Message should not save without a subject" do
     m = Message.new( body: 'A body is there but no subject')
     assert !m.save, 'Message should not save without a subject'
   end
   
   # negative test
   test "Message should not save without a body" do
     m = Message.new( subject: 'Message without body')
     assert !m.save, 'Message should not save without a body'
   end
   
   # negative test   
   test "Message body should have 40 chars at least" do
     m = Message.new(subject: 'Message with short body', body: 'A short body')
     assert !m.save, 'Message should not save whith short body'
   end
   
   # posititve test
   test "Message with subject and valid body should save" do
     m = create_valid_message(subject: 'A valid message')
     assert m.save, 'Message generated by create_valid_message should save'
   end
   
end
